name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v5
      with:
        node-version: 20
        cache: 'npm'
    - name: Setup project
      uses: bpmn-io/actions/setup@latest
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run all